default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
        -   id: autoflake
            args: [--remove-all-unused-imports, --in-place]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
      - id: isort
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
